### ISSUE TITLE
deallocation exception on nvidia

### ISSUE THREAD

**Issue by paulvironova** [paulvironova/emgucvstresstest#4]
Running the stress test on nvidia/win 10 gives this
```
C:\Users\PaulD\Desktop\emgucvstresstest>bin\x64\Debug\ConsoleApp1.exe
todiloo! Emgu GPU is GeForce GTX 1060 3GB
42   0.0    0.0    0.0    0.0    0.0    0.0    0.0    1.0
.
snip
.
573231   0.0    1.0    0.0    0.0    0.0    1.0    1.0    0.0
573261   1.0    0.0    1.0    1.0    1.0    0.0    0.0    1.0

Unhandled Exception: Emgu.CV.Util.CvException: OpenCV: u->refcount == 0 && "UMat deallocation error: some derived Mat is still alive"
   at Emgu.CV.CvInvoke.CvErrorHandler(Int32 status, IntPtr funcName, IntPtr errMsg, IntPtr fileName, Int32 line, IntPtr userData)
   at Emgu.CV.UMatInvoke.cveUMatRelease(IntPtr& mat)
   at Emgu.CV.UMat.DisposeObject()
   at Emgu.Util.DisposableObject.Finalize()
573291   0.0    1.0    0.0    0.0    0.0    1.0    1.0    0.0
573291   2.7    3.7    2.7    2.7    2.7    3.7    3.7    2.7
```

**Comment by paulvironova** [comment]
Happened again, with the same output, this time after approx. two hours and most likely when there was load from something else on the system.

**Comment by paulvironova** [comment]
Happened again, with the same output, this time after approx. two hours and most likely when there was load from something else on the system.
